#include <Wire.h> // I2C iletişimi için kütüphane
#include <Adafruit_MPU6050.h> // MPU6050 sensörü için kütüphane
#include <Adafruit_Sensor.h> // Sensör genel kütüphanesi
#include <SPI.h> // SPI iletişimi için kütüphane
#include <SD.h> // SD kart işlemleri için kütüphane
#include <U8g2lib.h> // OLED ekran için kütüphane
#include <Servo.h> // Servo motor kontrolü için kütüphane

// Nesne tanımları
Adafruit_MPU6050 mpu; // MPU6050 sensörü nesnesi
Servo servoMotor1; // Birinci servo motor nesnesi
Servo servoMotor2; // İkinci servo motor nesnesi
U8G2_SSD1306_128X64_NONAME_F_SW_I2C u8g2(U8G2_R0, /* clock=*/ SCL, /* data=*/ SDA, /* reset=*/ U8X8_PIN_NONE); // OLED ekran nesnesi

// Sabitler
const int chipSelect = 53; // SD kartın Chip Select pini, Arduino Mega için 53
bool sdInitialized = false; // SD kartın başlatılıp başlatılmadığını takip eden değişken

void setup() {
  Serial.begin(115200); // Seri iletişimi başlat
    while (!Serial); // Seri bağlantı hazır olana kadar bekle

      // Servo motorları tanımla
        servoMotor1.attach(9); // Birinci servo motoru 9 numaralı pine bağla
          servoMotor2.attach(10); // İkinci servo motoru 10 numaralı pine bağla

            // OLED ekranı başlat
              u8g2.begin(); // OLED ekranı başlat
                u8g2.setFont(u8g2_font_ncenB08_tr); // Ekran fontunu ayarla
                  u8g2.clearBuffer(); // Ekran tamponunu temizle
                    u8g2.setCursor(0, 10); // İmleci 0,10 pozisyonuna getir
                      u8g2.print("MPU6050 Test"); // Ekrana yazı yaz
                        u8g2.sendBuffer(); // Tamponu ekrana gönder

                          // MPU6050 sensörünü başlat
                            if (!mpu.begin()) { // Sensör başlatılamazsa
                                u8g2.clearBuffer(); // Ekran tamponunu temizle
                                    u8g2.setCursor(0, 30); // İmleci 0,30 pozisyonuna getir
                                        u8g2.print("MPU6050 not found"); // Hata mesajı yaz
                                            u8g2.sendBuffer(); // Tamponu ekrana gönder
                                                while (1) { // Sonsuz döngüye gir
                                                      delay(10); // 10 milisaniye bekle
                                                          }
                                                            }

                                                              Serial.print("Initializing SD card..."); // SD kart başlatma mesajı
                                                                // SD kartı başlat
                                                                  if (SD.begin(chipSelect)) { // SD kart başlatılırsa
                                                                      Serial.println("SD card initialized successfully."); // Başarı mesajı
                                                                          sdInitialized = true; // SD kartın başlatıldığını işaretle
                                                                              // MPU6050 veri dosyasını kontrol et ve oluştur
                                                                                  if (!SD.exists("mpu6050.txt")) { // Dosya yoksa
                                                                                        Serial.println("Dosya mevcut değil, oluşturuluyor..."); // Dosya oluşturma mesajı
                                                                                              File dataFile = SD.open("mpu6050.txt", FILE_WRITE); // Dosyayı yazma modunda aç
                                                                                                    if (dataFile) { // Dosya açılabilirse
                                                                                                            dataFile.println("Accelerometer – m/s^2"); // Başlık yaz
                                                                                                                    dataFile.println("Gyroscope – rps"); // Başlık yaz
                                                                                                                            dataFile.println("Temperature"); // Başlık yaz
                                                                                                                                    dataFile.close(); // Dosyayı kapat
                                                                                                                                            Serial.println("Dosya başarıyla oluşturuldu."); // Başarı mesajı
                                                                                                                                                  } else {
                                                                                                                                                          Serial.println("Dosya oluşturulurken hata oluştu."); // Hata mesajı
                                                                                                                                                                }
                                                                                                                                                                    }
                                                                                                                                                                      } else {
                                                                                                                                                                          Serial.println("SD card initialization failed."); // Başarısızlık mesajı
                                                                                                                                                                              sdInitialized = false; // SD kartın başlatılamadığını işaretle
                                                                                                                                                                                }
                                                                                                                                                                                }

                                                                                                                                                                                void writeToSD(File &file, const char *data) {
                                                                                                                                                                                  if (file) { // Dosya açılabilirse
                                                                                                                                                                                      file.println(data); // Veriyi dosyaya yaz
                                                                                                                                                                                          file.close(); // Dosyayı kapat
                                                                                                                                                                                            } else {
                                                                                                                                                                                                Serial.println("SD kart dosyası açılırken hata oluştu."); // Hata mesajı
                                                                                                                                                                                                  }
                                                                                                                                                                                                  }

                                                                                                                                                                                                  void loop() {
                                                                                                                                                                                                    sensors_event_t a, g, temp; // Sensör verisi için değişkenler
                                                                                                                                                                                                      mpu.getEvent(&a, &g, &temp); // Sensör verisini al

                                                                                                                                                                                                        // Seri monitöre yazdır
                                                                                                                                                                                                          Serial.print("Acceleration X: ");
                                                                                                                                                                                                            Serial.print(a.acceleration.x, 2); // İki ondalık basamak ile yazdır
                                                                                                                                                                                                              Serial.print(", Y: ");
                                                                                                                                                                                                                Serial.print(a.acceleration.y, 2); // İki ondalık basamak ile yazdır
                                                                                                                                                                                                                  Serial.print(", Z: ");
                                                                                                                                                                                                                    Serial.print(a.acceleration.z, 2); // İki ondalık basamak ile yazdır
                                                                                                                                                                                                                      Serial.println(" m/s^2");

                                                                                                                                                                                                                        Serial.print("Rotation X: ");
                                                                                                                                                                                                                          Serial.print(g.gyro.x, 2); // İki ondalık basamak ile yazdır
                                                                                                                                                                                                                            Serial.print(", Y: ");
                                                                                                                                                                                                                              Serial.print(g.gyro.y, 2); // İki ondalık basamak ile yazdır
                                                                                                                                                                                                                                Serial.print(", Z: ");
                                                                                                                                                                                                                                  Serial.print(g.gyro.z, 2); // İki ondalık basamak ile yazdır
                                                                                                                                                                                                                                    Serial.println(" rad/s");

                                                                                                                                                                                                                                      Serial.print("Temperature: ");
                                                                                                                                                                                                                                        Serial.print(temp.temperature, 2); // İki ondalık basamak ile yazdır
                                                                                                                                                                                                                                          Serial.println(" degC");

                                                                                                                                                                                                                                            // Verileri SD karta yaz
                                                                                                                                                                                                                                              if (sdInitialized) { // SD kart başlatılmışsa
                                                                                                                                                                                                                                                  File dataFile = SD.open("mpu6050.txt", FILE_WRITE); // Dosyayı yazma modunda aç
                                                                                                                                                                                                                                                      if (dataFile) { // Dosya açılabilirse
                                                                                                                                                                                                                                                            dataFile.print("Accelerometer – m/s^2\n");
                                                                                                                                                                                                                                                                  dataFile.print(a.acceleration.x, 2); dataFile.print(", ");
                                                                                                                                                                                                                                                                        dataFile.print(a.acceleration.y, 2); dataFile.print(", ");
                                                                                                                                                                                                                                                                              dataFile.print(a.acceleration.z, 2); dataFile.print("\n");

                                                                                                                                                                                                                                                                                    dataFile.print("Gyroscope – rps\n");
                                                                                                                                                                                                                                                                                          dataFile.print(g.gyro.x, 2); dataFile.print(", ");
                                                                                                                                                                                                                                                                                                dataFile.print(g.gyro.y, 2); dataFile.print(", ");
                                                                                                                                                                                                                                                                                                      dataFile.print(g.gyro.z, 2); dataFile.print("\n");

                                                                                                                                                                                                                                                                                                            dataFile.print("Temperature\n");
                                                                                                                                                                                                                                                                                                                  dataFile.print(temp.temperature, 2); dataFile.print(" degC\n");
                                                                                                                                                                                                                                                                                                                        dataFile.close(); // Dosyayı kapat
                                                                                                                                                                                                                                                                                                                              Serial.println("sd karta veri yazıldı"); // Başarı mesajı
                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                        Serial.println("SD kart dosyası açılırken hata oluştu."); // Hata mesajı
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                // Servo motorları kontrol et
                                                                                                                                                                                                                                                                                                                                                  int servoPos1 = map(g.gyro.x, -4.3, +4.3, 0, 180); // Birinci servo için konum hesapla
                                                                                                                                                                                                                                                                                                                                                    servoMotor1.write(servoPos1); // Birinci servoyu ayarla
                                                                                                                                                                                                                                                                                                                                                      int servoPos2 = map(g.gyro.y, -4.3, +4.3, 0, 180); // İkinci servo için konum hesapla
                                                                                                                                                                                                                                                                                                                                                        servoMotor2.write(servoPos2); // İkinci servoyu ayarla

                                                                                                                                                                                                                                                                                                                                                          // OLED ekranına yazdır
                                                                                                                                                                                                                                                                                                                                                            u8g2.clearBuffer(); // Ekran tamponunu temizle
                                                                                                                                                                                                                                                                                                                                                              u8g2.setCursor(0, 10); // İmleci ayarla
                                                                                                                                                                                                                                                                                                                                                                u8g2.print("Accelerometer – m/s^2");
                                                                                                                                                                                                                                                                                                                                                                  u8g2.setCursor(0, 20); // İmleci ayarla
                                                                                                                                                                                                                                                                                                                                                                    u8g2.print(a.acceleration.x, 2); // X ivmesini yazdır
                                                                                                                                                                                                                                                                                                                                                                      u8g2.print(", ");
                                                                                                                                                                                                                                                                                                                                                                        u8g2.print(a.acceleration.y, 2); // Y ivmesini yazdır
                                                                                                                                                                                                                                                                                                                                                                          u8g2.print(", ");
                                                                                                                                                                                                                                                                                                                                                                            u8g2.print(a.acceleration.z, 2); // Z ivmesini yazdır

                                                                                                                                                                                                                                                                                                                                                                              u8g2.setCursor(0, 30); // İmleci ayarla
                                                                                                                                                                                                                                                                                                                                                                                u8g2.print("Gyroscope – rps");
                                                                                                                                                                                                                                                                                                                                                                                  u8g2.setCursor(0, 40); // İmleci ayarla
                                                                                                                                                                                                                                                                                                                                                                                    u8g2.print(g.gyro.x, 2); // X dönüş hızını yazdır
                                                                                                                                                                                                                                                                                                                                                                                      u8g2.print(", ");
                                                                                                                                                                                                                                                                                                                                                                                        u8g2.print(g.gyro.y, 2); // Y dönüş hızını yazdır
                                                                                                                                                                                                                                                                                                                                                                                          u8g2.print(", ");
                                                                                                                                                                                                                                                                                                                                                                                            u8g2.print(g.gyro.z, 2); // Z dönüş hızını yazdır

                                                                                                                                                                                                                                                                                                                                                                                              u8g2.setCursor(0, 50); // İmleci ayarla
                                                                                                                                                                                                                                                                                                                                                                                                u8g2.print("Temperature");
                                                                                                                                                                                                                                                                                                                                                                                                  u8g2.setCursor(0, 60); // İmleci ayarla
                                                                                                                                                                                                                                                                                                                                                                                                    u8g2.print(temp.temperature, 2); // Sıcaklığı yazdır
                                                                                                                                                                                                                                                                                                                                                                                                      u8g2.print(" degC");
                                                                                                                                                                                                                                                                                                                                                                                                        u8g2.sendBuffer(); // Tamponu ekrana gönder

                                                                                                                                                                                                                                                                                                                                                                                                          delay(1000); // Bekleme süresi (1 saniye)
                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                          